// Repositories
export const AGENT_REPOSITORY = 'AGENT_REPOSITORY';


// Services
export const AGENT_SERVICE = 'AGENT_SERVICE';


// Use Cases
export const CREATE_AGENT_USE_CASE = 'CREATE_AGENT_USE_CASE';
export const GET_ALL_AGENTS_USE_CASE = 'GET_ALL_AGENTS_USE_CASE';
export const GET_AGENT_BY_ID_USE_CASE = 'GET_AGENT_BY_ID_USE_CASE';
export const UPDATE_AGENT_USE_CASE = 'UPDATE_AGENT_USE_CASE';
export const DELETE_AGENT_USE_CASE = 'DELETE_AGENT_USE_CASE';
export const EXECUTE_AGENT_USE_CASE = 'EXECUTE_AGENT_USE_CASE';

// Controllers
export const AGENT_CONTROLLER = 'AGENT_CONTROLLER';

// User Feature Constants
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CREATE_USER_USE_CASE = 'CREATE_USER_USE_CASE';
export const GET_USER_BY_ID_USE_CASE = 'GET_USER_BY_ID_USE_CASE';
export const GET_ALL_USERS_USE_CASE = 'GET_ALL_USERS_USE_CASE';
export const UPDATE_USER_USE_CASE = 'UPDATE_USER_USE_CASE';
export const DELETE_USER_USE_CASE = 'DELETE_USER_USE_CASE';
export const USER_CONTROLLER = 'USER_CONTROLLER';
